# Generated by Django 3.0.4 on 2020-04-02 22:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='foto_patente',
            field=models.FileField(blank=True, upload_to=api.models.get_upload_path),
        ),
    ]
