# Generated by Django 3.0.4 on 2020-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='origen',
            name='longitud',
            field=models.CharField(default='-33.4035323', max_length=20),
            preserve_default=False,
        ),
    ]
