# Generated by Django 3.0.4 on 2020-03-16 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_admin', models.CharField(max_length=20, unique=True)),
                ('password_admin', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_camion', models.CharField(max_length=20)),
                ('marca_camion', models.CharField(max_length=20)),
                ('modelo_camion', models.CharField(max_length=20)),
                ('capacidad_camion', models.CharField(max_length=20)),
                ('nombre_conductor_principal', models.CharField(max_length=20)),
                ('apellido_conductor_principal', models.CharField(max_length=20)),
                ('telefono_conductor_principal', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('QR', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Despachador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_despachador', models.CharField(max_length=20, unique=True)),
                ('password_despachador', models.CharField(max_length=128)),
                ('rut_despachador', models.CharField(max_length=20)),
                ('nombre_despachador', models.CharField(max_length=20)),
                ('apellido_despachador', models.CharField(max_length=20)),
                ('telefono_despachador', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destino', models.CharField(max_length=20)),
                ('nombre_propietario', models.CharField(max_length=20)),
                ('rut_propietario', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('latitud', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
                ('id_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Destino')),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_origen', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('latitud', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_de_coste', models.CharField(max_length=20, unique=True)),
                ('nombre_proyecto', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=20)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('mandante', models.CharField(max_length=20)),
                ('rut_mandante', models.CharField(max_length=20)),
                ('mandante_final', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subcontratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=20)),
                ('nombre_subcontratista', models.CharField(max_length=20)),
                ('nombre_contacto', models.CharField(max_length=20)),
                ('apellido_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.CharField(max_length=20)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Suborigen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_suborigen', models.CharField(max_length=20)),
                ('activo', models.CharField(max_length=20)),
                ('id_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Origen')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('nombre_subcontratista', models.CharField(max_length=20)),
                ('rut_subcontratista', models.CharField(max_length=20)),
                ('nombre_conductor_principal', models.CharField(max_length=20)),
                ('apellido_conductor_principal', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=20)),
                ('patente', models.CharField(max_length=20)),
                ('volumen', models.CharField(max_length=20)),
                ('tipo_material', models.CharField(max_length=20)),
                ('punto_origen', models.CharField(max_length=20)),
                ('punto_suborigen', models.CharField(max_length=20)),
                ('punto_destino', models.CharField(max_length=20)),
                ('contador_impresiones', models.IntegerField()),
                ('id_despachador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Despachador')),
            ],
        ),
        migrations.RemoveField(
            model_name='personal_controladores_frentes_proyectos',
            name='id_personal_controlador_frentes',
        ),
        migrations.RemoveField(
            model_name='personal_controladores_frentes_proyectos',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='proyectos_contratistas',
            name='id_contratista',
        ),
        migrations.RemoveField(
            model_name='proyectos_contratistas',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='proyectos_contratistas_camiones',
            name='id_camion',
        ),
        migrations.RemoveField(
            model_name='proyectos_contratistas_camiones',
            name='id_proyecto_contratista',
        ),
        migrations.RemoveField(
            model_name='punto_destino',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='punto_origen',
            name='id_proyecto',
        ),
        migrations.DeleteModel(
            name='Camiones',
        ),
        migrations.DeleteModel(
            name='Contratista',
        ),
        migrations.DeleteModel(
            name='Personal_controladores_frentes',
        ),
        migrations.DeleteModel(
            name='Personal_controladores_frentes_proyectos',
        ),
        migrations.DeleteModel(
            name='Proyectos',
        ),
        migrations.DeleteModel(
            name='Proyectos_contratistas',
        ),
        migrations.DeleteModel(
            name='Proyectos_contratistas_camiones',
        ),
        migrations.DeleteModel(
            name='Punto_destino',
        ),
        migrations.DeleteModel(
            name='Punto_origen',
        ),
        migrations.AddField(
            model_name='origen',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AddField(
            model_name='destino',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AddField(
            model_name='despachador',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AddField(
            model_name='camion',
            name='id_subcontratista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subcontratista'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
    ]
