# Generated by Django 3.0.4 on 2020-05-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_origen_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origen',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id_qr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
