# Generated by Django 3.0.4 on 2020-03-17 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200316_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despachador',
            name='username_despachador',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AlterField(
            model_name='despachador',
            name='rut_despachador',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='mandante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='mandante_final',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ubicacion',
            field=models.CharField(max_length=50),
        ),
    ]
