# Generated by Django 3.0.4 on 2020-03-17 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200317_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='id_subcontratista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Subcontratista'),
        ),
        migrations.AlterField(
            model_name='despachador',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AlterField(
            model_name='material',
            name='id_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Destino'),
        ),
        migrations.AlterField(
            model_name='origen',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AlterField(
            model_name='subcontratista',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AlterField(
            model_name='suborigen',
            name='id_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Origen'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id_despachador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Despachador'),
        ),
    ]
