# Generated by Django 3.0.4 on 2020-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200501_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='direccion',
        ),
        migrations.AddField(
            model_name='destino',
            name='calle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='destino',
            name='comuna',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='destino',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
