# Generated by Django 3.0.4 on 2020-03-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200322_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='api.Proyecto'),
        ),
        migrations.AlterField(
            model_name='despachador',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachadores', to='api.Proyecto'),
        ),
    ]
