# Generated by Django 3.0.4 on 2020-03-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200322_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='despachador',
            options={'verbose_name_plural': 'Despachadores'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name_plural': 'Proyectos'},
        ),
    ]
