# Generated by Django 3.0.4 on 2020-03-23 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200323_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='api.Proyecto'),
        ),
    ]
