# Generated by Django 3.0.4 on 2020-03-23 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200323_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_proyecto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='api.Proyecto'),
        ),
    ]
