# Generated by Django 3.0.4 on 2020-03-23 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200323_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='api.Proyecto'),
        ),
    ]
