# Generated by Django 3.0.4 on 2020-03-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200323_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='material',
            name='id_destino',
        ),
        migrations.RemoveField(
            model_name='origen',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='subcontratista',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='suborigen',
            name='id_origen',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='id_despachador',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AlterField(
            model_name='despachador',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.DeleteModel(
            name='Camion',
        ),
        migrations.DeleteModel(
            name='Destino',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Origen',
        ),
        migrations.DeleteModel(
            name='Subcontratista',
        ),
        migrations.DeleteModel(
            name='Suborigen',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
