# Generated by Django 3.0.4 on 2020-03-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200323_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='id_proyecto',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='despachador',
            old_name='id_proyecto',
            new_name='proyecto',
        ),
    ]
