# Generated by Django 3.0.4 on 2020-03-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200323_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
        migrations.AlterField(
            model_name='despachador',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proyecto'),
        ),
    ]
